# Site
repository: idea360/idea360.github.io
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Chris Kedzierski
title: Leadership/SRE/DevOps
email: chris@ked.ski
#website: chris.ked.ski
phone: 415-555-1212

# Dark Mode (true/false/never)
darkmode: true

# Social links
# twitter_username: facespics
github_username:  idea360
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
#instagram_username: jameswgrant
linkedin_username: chris-kedzierski-162191282
# xing_username: jekyll
# pinterest_username: jekyll
# youtube_username: globalmtb
# googleplus_username: +jekyll
# orcid_username: 0000-0000-0000-0000

# Additional icon links
#additional_links:
#- title: itsgoingto.be
#  icon: fas fa-globe
#  url: https://www.itsgoingto.be
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  I am a hands-on technical leader with extensive experience leading and growing Site Reliability Engineering (SRE) teams to deliver scalable, resilient, and high-performing systems. With a strong technical foundation and a passion for solving complex infrastructure challenges, I focus on driving operational excellence, fostering collaborative team environments, and aligning technical strategies with business goals. My mission is to build systems and teams that thrive under pressure, ensuring reliability and innovation go hand in hand.
content:
  - title: Experience # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Alation Inc.
        link: https://www.alation.com/
        # link_text: boringcompany.com
        sub_title: Sr Engineering Manager
        caption: 2019 - Present
        quote: >
          Technical leadership driving Alation's SaaS operations and infrastructure.
        description: | # this will include new lines to allow paragraphs
           Led a team of 8 Site Reliability Engineers to enhance system reliability and optimize cloud infrastructure for 1,000 users, achieving a 33% cost reduction through strategic spend management and observability improvements. Spearheaded the transition to a SaaS model, improved deployment frequency by 30% with Infrastructure-as-Code, and ensured FedRAMP compliance within a 3-month audit timeline. 
      - layout: left 
        title: GoBalto/Oracle
        link: https://www.oracle.com/corporate/pressrelease/oracle-buys-gobalto-101718.html
        sub_title: Senior SRE
        caption: 2018 - 2019
        quote: >
          Aquired by Oracle.
        description:
          Developed and scaled next-generation Kubernetes platforms, enhancing system resilience and mentoring engineers in high-availability best practices. Supported the Oracle acquisition by leading third-party code audits and transitioning infrastructure from AWS to Oracle Cloud Infrastructure, improving reliability and compliance.
      - layout: left
        title: Alation Inc. 
        link: https://www.alation.com/
        sub_title: DevOps Engineer
        caption: 2016 - 2018 
        quote: >
          First DevOps hire 
        description: 
          As the first DevOps hire, scaled CI/CD pipelines and infrastructure to support an engineering team’s growth from 5 to 40, ensuring seamless continuous integration and delivery. Contributed directly to code for backup, restore, high availability, and configuration management, enhancing operational reliability and robustness.
      - layout: left
        title: Skype / Microsoft
        link: https://www.skype.com/
        sub_title: Service Engineer 
        caption: 2010 - 2016
        quote: >
          Shifted from Operations to Internal Tooling to scale CI/CD.
        description:
          Implemented a hybrid cloud infrastructure integrating Data Centers and Azure, boosting system availability by 20% and enhancing deployment reliability by reducing failure rates by 25% through optimized CI/CD pipelines. Led internal engineering system improvements and managed tools like Jira, Confluence, Nexus, and QuickBuild, increasing productivity and reducing manual interventions.
      - layout: left 
        title: Logica CMG
        link: https://www.cgi.com/
        caption: 2007 - 2010
        sub_title: System Administrator
        quote: >
          Focused on development environment management
        description:
          Led post-acquisition system integrations and IT infrastructure improvements and enhancing inter-office connectivity for seamless collaboration.
      - layout: left
        title: Infradapt
        link: https://www.infradapt.com/
        caption: 2005-2007
        sub_title: Network Engineer
        quote: >
          A lot of miles on my car.
        description:
          Managed SMB networks and delivered customized communication solutions while providing on-site IT support.

  - title: Skills # Title for the section
    layout: text # Type of content section (list/text)
    content: | 
      **Technical Skills:** Kubernetes, Helm, Terraform, AWS, CI/CD (Jenkins, Harness), Observability (Datadog, Prometheus, Grafana), Scripting (Bash, Python), Ansible
      
      **Incident Management & Reliability:** Incident Response, Operational Readiness, High-Availability System Design
      
      **Leadership & Collaboration:** Team Building, Strategic Planning, Mentorship, Cross-functional Collaboration
  
  - title: Fun
    layout: text
    content: | # this will include new lines to allow paragraphs
      Alongside my interests in networks and software engineering some of my other interests and hobbies are:
      - Snowboarding
      - Watches
      - Guitar
      - Music
  
      ![Trees](/images/landscape-trees.jpg "Trees")

# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
