# Site
repository: idea360/idea360.github.io
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Chris Kedzierski
title: SRE, DevOps, & Leadership 
email: chris@ked.ski
#website: chris.ked.ski
#phone: 415-555-1212

# Dark Mode (true/false/never)
darkmode: true

# Social links
# twitter_username: facespics
github_username:  idea360
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
#instagram_username: jameswgrant
linkedin_username: chris-kedzierski-162191282
# xing_username: jekyll
# pinterest_username: jekyll
# youtube_username: globalmtb
# googleplus_username: +jekyll
# orcid_username: 0000-0000-0000-0000

# Additional icon links
#additional_links:
#- title: itsgoingto.be
#  icon: fas fa-globe
#  url: https://www.itsgoingto.be
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  I’m a hands-on technical leader passionate about building, deploying, and scaling high-performing systems. Over the years, I’ve had the privilege of working in, leading, and growing DevOps and Site Reliability Engineering (SRE) teams, focusing on solving complex challenges. My approach combines a solid technical foundation with a drive to foster collaborative, high-trust team environments. I align technical strategies with business goals to deliver impactful projects for all company levels. For me, success is about creating trust so that everyone can be at their best.
content:
  - title: Experience # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Alation Inc.
        link: https://www.alation.com/
        # link_text: boringcompany.com
        sub_title: Sr Engineering Manager
        caption: 2019 - Present
        quote: >
          Driving Operations, Oobservability, Tooling, & FedRAMP with Hands-on Leadership.
        description: | # this will include new lines to allow paragraphs
           I spearheaded the transition to a SaaS model with a managed service offering then migration into a multi-tenant environment. I led a team of 8 Site Reliability Engineers to enhance system reliability and optimize cloud infrastructure for thousands of users spanning multiple AWS regions. I also led the implimentation of the Incident Management process with observability tools (Pagerduty, Datadog, Prometheus, and Grafana). I improved production deployment frequency and built a FedRAMP compliance within a 3-month audit timeline.
      - layout: left 
        title: GoBalto/Oracle
        link: https://www.oracle.com/corporate/pressrelease/oracle-buys-gobalto-101718.html
        sub_title: Senior SRE
        caption: 2018 - 2019
        quote: >
          Kubernetes Scaling & Cloud Migration Leadership - Aquired by Oracle.
        description:
          Developed and scaled next-generation Kubernetes platforms, enhancing system resilience and mentoring engineers in high-availability best practices. Supported the Oracle acquisition by leading third-party code audits and transitioning infrastructure from AWS to Oracle Cloud Infrastructure, improving reliability and compliance.
      - layout: left
        title: Alation Inc. 
        link: https://www.alation.com/
        sub_title: DevOps Engineer
        caption: 2016 - 2018 
        quote: >
          First DevOps hire - CI/CD, On-Prem & Operation Code. 
        description: 
          First DevOps hire; scaled CI/CD pipelines and infrastructure to support engineering team growth from 5 to 100. Directly contributed to backup, restore, high availability, and configuration management code, improving operational reliability and robustness.
      - layout: left
        title: Skype / Microsoft
        link: https://www.skype.com/
        sub_title: Service Engineer 
        caption: 2010 - 2016
        quote: >
          Bootstrapped Internal Tooling, Hybrid Cloud Integration & CI/CD
        description:
           Implemented a hybrid cloud infrastructure integrating Data Centers with Azure, boosting system availability and enhancing deployment reliability by reducing build failure rates through optimized CI/CD pipelines (Maven, Ant). Led internal engineering system improvements and managed tools like Jira, Confluence, Nexus, and QuickBuild to increase productivity.
      - layout: left 
        title: Logica CMG
        link: https://www.cgi.com/
        caption: 2007 - 2010
        sub_title: System Administrator
        quote: >
          Development Environments, Local Infrastructure, & Integrations.
        description:
          Led post-acquisition system integrations and IT infrastructure improvements and enhancing inter-office connectivity for seamless collaboration.
      - layout: left
        title: Infradapt
        link: https://www.infradapt.com/
        caption: 2005-2007
        sub_title: Network Engineer
        quote: >
          Cisco, Networking Fundamentals, & Learning.
        description:
          Managed SMB networks and delivered customized communication solutions while providing on-site IT support.

  - title: Skills # Title for the section
    layout: text # Type of content section (list/text)
    content: | 
      **_Technical Skills_:** Kubernetes, Helm, Terraform, AWS, CI/CD (Jenkins, Harness), Observability (Datadog, Prometheus, Grafana), Scripting (Bash, Python), Ansible
      
      **_Incident Management & Reliability_:** Incident Response, Operational Readiness, High-Availability System Design
      
      **_Leadership & Collaboration_:** Team Building, Strategic Planning, Mentorship, Cross-functional Collaboration
  
  - title: Fun
    layout: text
    content: | # this will include new lines to allow paragraphs
      Alongside my interests in engineering my other interests are:
      - Snowboarding
      - Watches
      - Guitar
      - Music

      ![Trees](/images/landscape-snow.jpg "Snow"){: width="200" }

# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
